[phases.setup]
nixPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Python backend built successfully'"]

[start]
cmd = "./start.sh" 