[phases.setup]
nixPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["pip3 install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Python backend built successfully'"]

[start]
cmd = "cd backend && python3 -m uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}" 